name: 'Build'
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          dotnet restore                        # install packages
          dotnet build -c Release --no-restore  # build
          echo "CZ_PLUGIN_VERSION=$(cat ${{ github.workspace }} | jq -r '.version')" >> $GITHUB_ENV
          echo "CZ_PLUGIN_NAME=$(cat ${{ github.workspace }} | jq -r '.name')" >> $GITHUB_ENV
          echo "CZ_NUGET_PATH=${{ github.workspace }}/bin/$(cat ${{ github.workspace }}/manifest.json | jq -r '.name').$(cat ${{ github.workspace }} | jq -r '.version')--${{ env.GITHUB_SHA }}.nupkg" >> $GITHUB_ENV
        
      - uses: actions/upload-artifact@v4
        with: 
          name: "${{ env.CZ_PLUGIN_NAME }}.${{ env.CZ_PLUGIN_VERSION }}.nupkg"
          path: "${{ env.CZ_NUGET_PATH }}"

      - uses: actions/upload-artifact@v4
        with: 
          name: "${{ env.CZ_PLUGIN_NAME }}.${{ env.CZ_PLUGIN_VERSION }}"
          path: "${{ github.workspace }}/bin/net8.0/"

      - name: Push GitHub NuGet Package
        run: |
          dotnet nuget add source --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
          dotnet nuget push "${{ env.CZ_NUGET_PATH }}" --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"
      